admin/src/web/controllers/service_controller.py
import math
from flask import session
from flask import Blueprint,redirect, render_template, request, url_for, flash
from src.core.models.service_model import Service
from src.core.models.institution_model import Institution
from src.core.models.type_model import Type
from src.core.models.config_model import Config
from src.web.helpers.auth import login_required, has_permission
from src.core.models import create_service
from src.web.helpers.session import get_current_institution
from src.core.models import create_service
from src.web.helpers.validations import verify_space, verify_vacio, verify_service,verify_lenghts
service_blueprint = Blueprint("service", __name__, url_prefix="/service")

@service_blueprint.get("/")
@service_blueprint.get("/<int:page>") 
@login_required
@has_permission("service_index")     
def index(page=1):
    config = Config.get_singleton()
    page_size = config.cant
    s, s_count = Service.paginate(
        page, page_size, inst=get_current_institution())
    '''divide la cantidad de todos los servicios en las filas con la cantidad de servicios que quiero por pagina'''
    page_count = math.ceil(s_count / page_size)
    return render_template(
        "service/index.html.jinja",
        s=s,
        s_count=s_count,
        page=page,
        page_count=page_count
    )


@login_required
@service_blueprint.route("/create_service",methods=['GET', 'POST'])  
@has_permission("service_create")  
def create():
    if request.method == 'POST':

        if verify_vacio(items=request.form.items()):

            if verify_space(items=request.form.items()):
                
                if not (verify_service(request.form['title'])) and verify_lenghts(request.form['title'], request.form['description']):
                    s = request.form['state']
                    '''type_id se guarda el valor de opciones que se selecciona en el formulario, estas opciones son los 
                       tipos de servicios que existen
                    s.lower() convierte la cadena "True" o "False" recibida en boolean
                    institution= session.get("inst_id") si ya existe un Servicio con "nombre1" deberia dejar crearlo 
                    por que seria para otra institucion, por simplicidad no dejo que se repitan aun cuando si se 
                    llamaran igual no serian el mismo'''
                    create_service (
                        title=request.form['title'],
                        description=request.form['description'],
                        state = (s.lower()=='true'),
                        keywords=request.form['keywords'], 
                        type_id=request.form['opciones'], 
                        institution= session.get("inst_id")
                    )
            else:
                flash("El servicio no pudo crearse ", "danger")
        else:
            flash("el campo no puede ser vacio", "danger")
            return render_template('service/create_service.html.jinja')

        return redirect(url_for("service.index"))

    return render_template('service/create_service.html.jinja')

@login_required
@service_blueprint.route("/update/<id>",methods=['GET', 'POST']) 
@has_permission("service_update") 
def update(id):
    serv = Service.find_by_id(id)
    '''Idem create() solamente que aca no se accede al estado de habilitacion ni a la institucion'''
    if verify_vacio(items=request.form.items()):
        if verify_space(items=request.form.items()):
            if verify_lenghts(request.form['title'], request.form['description']):
                    title= request.form['title'],
                    description= request.form['description'],
                    keywords=request.form['keywords']
                    type= request.form['opciones']
                    serv.update_service_database(title,description,keywords,type)
                    flash("El servicio se actualizo correctamente ", "succes")
        else:
            flash("El servicio no pudo actualizarse ", "danger")
    else:
        flash("el campo no puede ser vacio", "danger")
    return redirect(url_for("service.index"))



@login_required
@service_blueprint.route("/delete/<id>",methods=['GET', 'POST'])  
@has_permission("service_destroy") 
def delete(id):
    '''Elimina un servicio y redirige al index de servicios'''
    s = Service.get_service_by_id(Service,id)
    s.delete()
    return redirect(url_for("service.index"))


@service_blueprint.route("/enable_disable/<id>",methods=['GET', 'POST'])
@login_required
@has_permission("service_update") 
def enable_disable(id): 
    '''Cambia el estado del servicio. Si estaba habilitado lo deshabilita y viceversa'''
    s = Service.get_service_by_id(Service,id)
    if s.habilite == True :
        s.habilite = False 
    else:
        s.habilite = True
    s.register_service_database()
    return redirect(url_for("service.index"))

admin/src/web/templates/service/create_service.html.jinja
{% extends "layout.html.jinja" %}

{% block main %}

<!-- Iconos fontawesome -->
<link rel="stylesheet" href="{{ url_for('static', filename='fontawesome/css/all.css') }}">

<!-- Crear Servicio -->
<p>
<h1 class="h3 mb-3 fw-normal"> Formulario de Creación de SERVICIO</h1>
</p>

<form action="{{ url_for('service.create') }} " method="POST" id="form_crear" name="form_crear" class="needs-validation"
    novalidate>
    <div class="row mb-4">
        <!-- nombre input -->
        <div class="col">
            <div class="form-outline shadow-sm p-1 mb-1 bg-black rounded">
                <label class="form-label" for="title"> <b> Nombre del Servicio</b> </label>
                <input type="text" id="title" name="title" class="form-control"
                    pattern="[a-zA-Zá-úÁ-ÚñÑ]+[a-zA-Zá-úÁ-ÚñÑ0-9 ]*" required />
                <div class="invalid-feedback">
                    Por favor, ingrese un nombre de Servicio válido.
                    <br>
                    El nombre de servicio debe tener entre 5 y 40 letras y digitos.
                    <br>
                    No puede comenzar con números ni contener símbolos.
                </div>
            </div>
        </div>
        <!-- description input -->
        <div class="col">
            <div class="form-outline shadow-sm p-1 mb-1 bg-black rounded">
                <label class="form-label" for="description_service "> <b> Descripcion del Servicio </b> </label>
                <input type="text" id="description" name="description" class="form-control"
                    pattern="[a-zA-Zá-úÁ-ÚñÑ]+[a-zA-Zá-úÁ-ÚñÑ0-9 ]*" required />
                <div class="invalid-feedback">
                    Por favor, ingrese una descripcion válida.
                    <br>
                    La descripcion debe tener entre 10 y 50 letras.
                    <br>
                    No puede comenzar con números ni contener símbolos.
                </div>
            </div>
        </div>
    </div>

    <!--  keywords input -->
    <div class="form-outline mb-4 shadow-sm p-1 mb-1 bg-black rounded">
        <label class="form-label" for="keywords"> <b> Palabaras clave de busqueda (Separar las palabras por , Ej:k1,k2,)
            </b> </label>
        <input type="text" id="keywords" name="keywords" class="form-control"
            pattern="^[a-zA-Zá-úÁ-ÚñÑ]+(?:,[a-zA-Zá-úÁ-ÚñÑ]+[0-9]*)*$" required /> 
            
        <div class="invalid-feedback">
            Por favor, ingrese palabras claves válidas.
            <br>
            Las palabras claves no pueden contener espacios en blanco.
        </div>
    </div>

    <!--  type input -->
    <div class="form-outline mb-4 shadow-sm p-1 mb-1 bg-black rounded">
        <label class="form-label" for="type"> <b> Tipo de Servicio </b> </label>
        <div>
            <label for="opciones">Elige una opción:</label>
            <select id="opciones" name="opciones">
                <option value="1">Analisis</option>
                <option value="2">Consultoria</option>
                <option value="3">Desarrollo</option>
            </select>
        </div>
    </div>
    <!--  input -->
    <div class="form-outline mb-4 shadow-sm p-1 mb-1 bg-black rounded">
        <label class="form-label" for="state"> <b> Estado de habilitacion </b> </label>
        <div>
            <label for="state">Elige una opción:</label>
            <select id="state" name="state">
                <option value='True'>Habilitar</option>
                <option value='False'>Deshabilitar</option>
            </select>
        </div>
    </div>

    <button type="submit" class="btn btn-success btn-lg btn-block"><i class="fa fa-save"></i> CREAR</button>
    <a class="btn btn-primary btn-lg btn-block" href="{{ url_for('service.index') }}" role="button">RETROCEDER</a>

</form>

{% endblock %}

admin/src/web/templates/service/index.html.jinja
{% extends "layout.html.jinja" %}


{% block main %}

<h1>Gestion de Servicios </h1>
<br>

<!-- tabla usuarios  -->

<div class="container">

    <div class="col-sm-10">
        <table>

            <th>
                <a href="{{ url_for('service.create') }}"> <button type="button" class="btn btn-warning ">
                        <i class="fa-solid fa-user-plus"></i>Agregar Servicio</button> </a>
            </th>
            <th></th>

        </table>
    </div>

    <br>

    <div class="col-md-15">
    {% if s_count > 0 %}
        <table class="table table-striped table-bordered">
            <thead>
                <tr class="bg-primary text-white">
                    <th>Nombre del Servicio</th>
                    <th>Tipo de Servicio</th>
                    <th>Descripcion</th>
                    <th>Palabaras Clave (Separar las palabras por , Ej: k1,k2)</th>
                    <th>Estado de Habilitacion </th>
                    <th>Operaciones </th>
                </tr>
            </thead>


            <tbody id="myTable">
                {% for i in s %}
                <tr>
                    <td> {{ i.title }}</td>
                    <td> {{ i.type.name }}</td> 
                    <td> {{ i.description}} </td>
                    <td> {{ i.keywords }} </td>
                    <!-- Esto es para no mostrar true o false cuando me traigo habilite -->
                    {% if i.habilite %}
                    <td> Habilitado </td>
                    {% else %}
                    <td> Deshabilitado </td>
                {% endif %}
                <td align="center">
                    <!-- Editar -->
                        <button type="button" class="btn btn-white" data-bs-toggle="modal"
                            data-bs-target="#modaledit{{i.id}}">
                            <i class="fa-solid fa-pen-to-square"></i> Editar
                        </button>
                    <!-- Eliminar -->
                        <a href="{{ url_for( 'service.delete',id = i.id )  }}" class="text-danger"
                            onClick="return confirm('¿Esta seguro que desea eliminar el servicio?');"><i
                                class="fa fa-fw fa-trash"></i>
                            Eliminar</a>
                            
                    <!-- Habilitar/Deshabilitar -->
                        <button type="button" class="btn btn-white">
                            <a href="{{ url_for( 'service.enable_disable',id = i.id )  }}"
                                onClick="return confirm('¿Esta seguro que desea cambiar el estado de habilitacion del servicio?');"><i
                                    class="fa fa-fw fa-trash"></i> Habilitar/Deshabilitar</a> <!--  -->
                        </button>
                    </td>
                </tr>

                
    </div>
</div>
</div>
</div>


{% endfor %}
</tbody>
</table>
    <!-- Paginacion -->
    <nav>
        <ul class="pagination">
            {% if page <= 1 %} <li class="page-item disabled">
                <a class="page-link"><i class="bi bi-arrow-left"></i></a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="{{ url_for('service.index', page=(page - 1)) }}"><i
                            class="bi bi-arrow-left"></i></a>
                </li>
                {% endif %}
                {% for i in range(1, page_count + 1) %}
                <li class="page-item{% if i == page %} active{% endif %}">
                    <a class="page-link" href="{{ url_for('service.index', page=i) }}">{{i}}</a>
                </li>
                {% endfor %}
                {% if page >= page_count %}
                <li class="page-item disabled">
                    <a class="page-link"><i class="bi bi-arrow-right"></i></a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="{{ url_for('service.index', page=(page + 1)) }}"><i
                            class="bi bi-arrow-right"></i></a>
                </li>
                {% endif %}
        </ul>
    </nav>
    {% else %}
    <h1>Todavía no hay Servicios registrados</h1>
    {% endif %}
</div>
</div>

<!-- Modificar -->
{% for i in s %}
<div class="modal fade" id="modaledit{{i.id}}" tabindex="-1" aria-labelledby="modaledit"
    aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="text-black" class="modal-title" id="modaledit"> <b>Modificar Servicio</b>
                    </h5>
            </div>
            <div class="modal-body">
                <form action="{{ url_for('service.update', id=i.id) }}" method="POST" class="needs-validation" novalidate>

                    <!-- Nombre de servicio input -->
                    <div class="form-outline mb-4 shadow-sm p-1 mb-1 bg-black rounded">
                        <label class="form-label" for="type"> <b> Nombre del Servicio </b> </label>
                        <input type="text" id="title" name="title" value="{{i.title}}"class="form-control" pattern="[a-zA-Zá-úÁ-ÚñÑ]+[a-zA-Zá-úÁ-ÚñÑ0-9 ]*" required>
                        <div class="invalid-feedback">
                            Por favor, ingrese un nombre de Servicio válido.
                            <br>
                            El nombre de servicio debe tener entre 5 y 40 letras y digitos.
                            <br>
                            No puede comenzar con números o símbolos ni terminar en símbolos.
                        </div>
                    </div>
                    <!-- tipo de servicio input -->
                    <div class="form-outline mb-4 shadow-sm p-1 mb-1 bg-black rounded">
                        <label class="form-label" for="type"> <b> Tipo de Servicio </b> </label>
                        <div>
                            <label for="opciones">Elige una opción:</label>
                            <select id="opciones" name="opciones">
                                <option value="1">Analisis</option>
                                <option value="2">Consultoria</option>
                                <option value="3">Desarrollo</option>
                            </select>
                        </div>
                    </div>
                    <!-- Descripcion input -->
                    <div class="form-outline mb-4 shadow-sm p-1 mb-1 bg-black rounded">
                        <label class="form-label" for="type"> <b> Descripcion del Servicio </b> </label>
                        <input type="text" id="description" name="description" value="{{i.description}}" class="form-control" 
                        pattern="[a-zA-Zá-úÁ-ÚñÑ]+[a-zA-Zá-úÁ-ÚñÑ0-9 ]*" required/>
                        <div class="invalid-feedback">
                            Por favor, ingrese una descripcion válida.
                            <br>
                            La descripcion debe tener entre 10 y 50 letras.
                            <br>
                            No puede comenzar con números ni contener símbolos.
                        </div>
                    </div>
                    <!-- Keywords input -->
                    <div class="form-outline mb-4 shadow-sm p-1 mb-1 bg-black rounded">
                        <label class="form-label" for="type"> <b> Palabras clave </b> </label>
                        <input type="text" id="keywords" name="keywords" value="{{ i.keywords }}" class="form-control" 
                        pattern="^[a-zA-Zá-úÁ-ÚñÑ]+(?:,[a-zA-Zá-úÁ-ÚñÑ]+[0-9]*)*$" required/>
                        <div class="invalid-feedback">
                            Por favor, ingrese palabras claves válidas.
                            <br>
                            Las palabras claves no pueden contener espacios en blanco.
                        </div>
                    </div>
                    <br>

                    <div>
                        <button type="button" class="btn btn-secondary btn-lg"
                            data-bs-dismiss="modal">Cerrar</button>
                        <button type="submit" class="btn btn-success btn-lg btn-block"><i
                                class="fa fa-save"></i>
                            Guardar</button>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
{% endfor %}

{% endblock %}