admin/src/web/controllers/user_controller.py
import json
import math
from flask import abort, Blueprint, redirect, render_template, request, url_for, session, flash
from flask_mail import Message
from src.core.models import crear_usuario
from src.core.models.user_model import User
from src.core.models.role_model import Role
from src.core.models.institution_model import Institution
from src.core.models.config_model import Config
from src.core.bcrypt import bcrypt
from src.web.mail import mail
from src.web.helpers.auth import login_required, has_permission
from src.web.helpers.validations import (
    validate_email,
    validate_username,
    validate_password,
    validate_first_name,
    validate_last_name,
    validate_active
)
from src.web.helpers.session import get_current_user
from src.web.helpers.tokens import get_serializer


user_blueprint = Blueprint("user", __name__, url_prefix="/user")

role_blueprint = Blueprint("role", __name__, url_prefix="/role")
user_blueprint.register_blueprint(role_blueprint)


@user_blueprint.get("/")
@user_blueprint.get("/<int:page>")
@login_required
@has_permission("user_index")
def index(page=1):
    page_size = Config.get_singleton().cant

    users, users_count = User.paginate(page, page_size, request.args.get("email"), request.args.get("filter"))
    page_count = math.ceil(users_count / page_size)

    return render_template(
        "user/index.html.jinja",
        users=users,
        users_count=users_count,
        page=page,
        page_count=page_count,
        filter_email=request.args.get("email", ""),
        filter_active=request.args.get("filter", "")
    )


def create_update(user=None, arglist=None):
    form = request.form

    if isinstance(user, int):
        user = User.get(user)

    args = {
        'email': validate_email,
        'username': validate_username,
        'password': validate_password,
        'first_name': validate_first_name,
        'last_name': validate_last_name,
        'activo': validate_active
    }

    kwargs = {}
    for key, fn in args.items():
        if arglist and key not in arglist:
            continue
        value, *err = fn(form, user)
        if value is None:
            if len(err) > 0:
                flash(err[0], "danger")
            break
        kwargs[key] = value
    else:
        if user:
            if user.has_role(Role.get_by_name("Super Administrador")) and args['activo'](form, user)[0] == False:
                flash("No se puede deshabilitar el usuario superadministrador", "danger")
                return None
            user.update(**kwargs)
        else:
            user = crear_usuario(**kwargs)
        return user
        
    return None


@user_blueprint.post("/create")
@login_required
@has_permission("user_create")
def create():
    if create_update():
        flash("¡Se creó el usuario de manera exitosa!", "success")
    
    return redirect(url_for("user.index"))


@user_blueprint.post("/update/<int:userid>")
@login_required
@has_permission("user_update")
def update(userid):
    arglist = ['email', 'username', 'first_name', 'last_name', 'activo']
    if request.form.get('change_password'):
        arglist.append('password')
        
    if create_update(userid, arglist):
        flash("¡Se actualizó el usuario de manera exitosa!", "success")
    
    return redirect(url_for("user.index"))


@user_blueprint.post("/delete/<int:userid>")
@login_required
@has_permission("user_destroy")
def delete(userid):
    user = User.get(userid)
    if user:
        if user.has_role(Role.get_by_name("Super Administrador")):
            flash("No se puede eliminar el usuario superadministrador", "danger")
        else:
            user.delete()
    else:
        flash(f"No se pudo eliminar el usuario con ID: {userid}")
    
    return redirect(url_for("user.index"))


@role_blueprint.get("/<int:userid>", endpoint="index")
@login_required
@has_permission("user_index")
def role_index(userid):
    user = User.get(userid)
    if not user:
        abort(404)
    
    roles = Role.get_all()
    insts = Institution.get_all()

    user_roles = []
    for ur in user.get_roles():
        user_roles.append({
            "role": Role.find_by_id(ur.role_id),
            "inst": Institution.find_by_id(ur.institution_id),
            "id": f"r{ur.role_id}-i{ur.institution_id or 0}"
        })
    
    user_roles_count = len(user_roles)
    
    return render_template(
        "user/roles.html.jinja",
        user=user,
        roles=roles,
        insts=insts,
        user_roles=user_roles,
        user_roles_count=user_roles_count
    )


@role_blueprint.post("/<int:userid>/add", endpoint="add")
@login_required
@has_permission("user_update")
def role_add(userid):
    user = User.get(userid)
    if not user:
        abort(404)
    
    roleid = request.form.get("roleid")
    role = Role.find_by_id(roleid) if roleid else None
    if not role:
        abort(404)
    
    if role.name == "Super Administrador":
        abort(404)
    
    instid = request.form.get("instid")
    inst = Institution.find_by_id(instid) if instid else None
    if not inst:
        abort(404)
    
    if user.has_role(role, inst):
        flash("Ya existe un rol similar para el usuario", "danger")
    else:
        user.add_role(role, inst)
        
    return redirect(url_for("user.role.index", userid=user.id))


@role_blueprint.post("/<int:userid>/remove/<int:roleid>", endpoint="remove")
@role_blueprint.post("/<int:userid>/remove/<int:roleid>/<int:instid>", endpoint="remove")
@login_required
@has_permission("user_update")
def role_remove(userid, roleid, instid=None):
    user = User.get(userid)
    if not user:
        abort(404)

    role = Role.find_by_id(roleid)
    if not role:
        abort(404)
    
    if role.name == "Super Administrador":
        abort(404)

    if instid:
        inst = Institution.find_by_id(instid)
        if not inst:
            abort(404)
    else:
        inst = None

    ok = user.remove_role(role, inst)
    if not ok:
        flash("No se pudo eliminar el rol", "danger")
    
    return redirect(url_for("user.role.index", userid=user.id))


@user_blueprint.route("/register", methods=["GET", "POST"])  
def register():
    if request.method == 'POST':
        user = create_update(arglist=['email', 'first_name', 'last_name'])
        if user:
            ser = get_serializer("confirmation")
            tok = ser.dumps({"user_id": user.id})

            msg = Message(
                "Confirmación de usuario",
                recipients=[user.email]
            )
            msg.html = render_template('email.html.jinja', token=tok)
            mail.send(msg)

            flash(
                "Le enviamos un enlace de confirmación a su casilla de correo electrónico. "
                "Por favor, confirme su correo antes de iniciar sesión.",
                "warning"
            )

            return redirect(url_for("auth.login"))
        else:
            return redirect(url_for("user.register"))
    elif request.method == 'GET':
        return render_template('register_user.html.jinja')


@user_blueprint.route("/confirm/<token>", methods=["GET", "POST"])
def confirm(token):
    try:
        ser = get_serializer("confirmation")
        data = ser.loads(token)
    except:
        abort(404)
    
    user_id = data.get('user_id')
    if user_id is None:
        abort(404)

    user = User.find_by_id(data['user_id'])
    if user is None:
        abort(404)
    
    if user.exists:
        abort(404)
    
    if request.method == 'POST':
        if create_update(user=user, arglist=['username', 'password']):
            flash("¡Su usuario ha sido confirmado exitosamente!", "success")
            return redirect(url_for("auth.login"))

    return render_template("user/confirm.html.jinja", token=token, user=user)


@user_blueprint.route("/profile", methods=["GET", "POST"]) 
@login_required  
def profile():
    user = get_current_user()
    if not user:
        abort(404)

    if request.method == "POST":
        arglist = ['username', 'first_name', 'last_name']
        if request.form.get('change_password'):
            arglist.append('password')
            
        if create_update(user=user, arglist=arglist):
            flash("¡Se actualizaron sus datos de manera exitosa!", "success")
    
    return render_template('user/profile.html.jinja', user=user)

admin/src/web/templates/user/confirm.html.jinja
{% extends 'layout.html.jinja' %}

{% block main %}
<div class="d-flex justify-content-center align-items-center">
  <div class="card">
    <div class="card-header">
      <h2>Confirmación de usuario</h2>
    </div>
    <form action="{{ url_for('user.confirm', token=token) }}" method="post" class="needs-validation" novalidate>
      <div class="card-body">
        <div class="row g-3">
          <div class="col-12">
            <label for="email" class="form-label">Email</label>
            <input type="email" class="form-control" id="email" name="email" value="{{ user.email }}" readonly>
          </div>
          <div class="col-12">
            <label for="username" class="form-label">Nombre de usuario (*)</label>
            <input type="text" class="form-control" id="username" name="username" pattern="[a-zA-Zá-úÁ-ÚñÑ][a-zA-Zá-úÁ-ÚñÑ0-9._]{2,18}[a-zA-Zá-úÁ-ÚñÑ0-9]" required>
            <div class="invalid-feedback">
              Por favor, ingrese un nombre de usuario válido.
              <br>
              El nombre de usuario debe tener entre 4 y 20 letras, dígitos, '.' y '_'.
              <br>
              No puede comenzar con números o símbolos ni terminar en símbolos.
            </div>
          </div>
          <div class="col-md-6">
            <label for="password" class="form-label">Contraseña (*)</label>
            <input type="password" class="form-control password-field" id="password" name="password" pattern="[^ ]{4,32}" required>
            <div class="invalid-feedback">
              Por favor, ingrese una contraseña válida.
              <br>
              Las contraseñas deben tener entre 4 y 32 carácteres, no pueden tener espacios.
            </div>
          </div>
          <div class="col-md-6">
            <label for="password_repeat" class="form-label">Repetir contraseña (*)</label>
            <input type="password" class="form-control confirm-password-field" id="password_repeat" name="password_repeat" required>
            <div class="invalid-feedback">
              Por favor, repita la contraseña aquí. Las contraseñas deben coincidir.
            </div>
          </div>
          <div class="col-12 mt-2">
            <span class="form-text">(*) Campo requerido</span>
          </div>
        </div>
      </div>
      <div class="card-footer d-flex justify-content-end">
        <button type="submit" class="btn btn-success">Confirmar</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

admin/src/web/templates/user/profile.html.jinja
{% extends "layout.html.jinja" %}

{% block main %}

<div class="d-flex justify-content-center align-items-center">
  <div class="card">
    <div class="card-header">
      <h2>Mi perfil</h2>
    </div>
    <form method="post" class="needs-validation" novalidate>
      <div class="card-body">
        <div class="row g-3">
          <div class="col-12">
            <label for="email" class="form-label">Email</label>
            <input type="email" class="form-control" id="email" value="{{ user.email }}" readonly>
          </div>
          <div class="col-12">
            <label for="username" class="form-label">Nombre de usuario (*)</label>
            <input type="text" class="form-control" id="username" name="username" value="{{ user.username }}" pattern="[a-zA-Zá-úÁ-ÚñÑ][a-zA-Zá-úÁ-ÚñÑ0-9._]{2,18}[a-zA-Zá-úÁ-ÚñÑ0-9]" required>
            <div class="invalid-feedback">
              Por favor, ingrese un nombre de usuario válido.
              <br>
              El nombre de usuario debe tener entre 4 y 20 letras, dígitos, '.' y '_'.
              <br>
              No puede comenzar con números o símbolos ni terminar en símbolos.
            </div>
          </div>
          <div class="col-md-6">
            <label for="first_name" class="form-label">Nombre/s (*)</label>
            <input type="text" class="form-control" id="first_name" name="first_name" value="{{ user.first_name }}" pattern="[a-zA-Zá-úÁ-ÚñÑ][a-zA-Zá-úÁ-ÚñÑ ]{0,22}[a-zA-Zá-úÁ-ÚñÑ]" required>
            <div class="invalid-feedback">
              Por favor, ingrese un nombre válido.
              <br>
              Los nombres solo pueden contener letras y espacios.
              <br>
              No pueden comenzar ni terminar con espacios.
            </div>
          </div>
          <div class="col-md-6">
            <label for="last_name" class="form-label">Apellido/s (*)</label>
            <input type="text" class="form-control" id="last_name" name="last_name" value={{ user.last_name }} pattern="[a-zA-Zá-úÁ-ÚñÑ][a-zA-Zá-úÁ-ÚñÑ ]{0,22}[a-zA-Zá-úÁ-ÚñÑ]" required>
            <div class="invalid-feedback">
              Por favor, ingrese un apellido válido.
              <br>
              Los apellidos solo pueden contener letras y espacios.
              <br>
              No pueden comenzar ni terminar con espacios.
            </div>
          </div>
          <div class="col-md-6">
            <label for="password" class="form-label">Contraseña</label>
            <input type="password" class="form-control password-field" id="password" name="password" disabled pattern="[^ ]{4,32}" required>
            <div class="invalid-feedback">
              Por favor, ingrese una contraseña válida.
              <br>
              Las contraseñas deben tener entre 4 y 32 carácteres, no pueden tener espacios.
            </div>
          </div>
          <div class="col-md-6">
            <label for="password_repeat" class="form-label">Repetir contraseña</label>
            <input type="password" class="form-control confirm-password-field" id="password_repeat" name="password_repeat" disabled required>
            <div class="invalid-feedback">
              Por favor, repita la contraseña aquí. Las contraseñas deben coincidir.
            </div>
          </div>
          <div class="col-12">
            <div class="form-check form-switch">
              <input type="checkbox" role="switch" class="form-check-input change-password" id="change_password" name="change_password">
              <label class="form-check-label" for="change_password">Cambiar contraseña</label>
            </div>
          </div>
          <div class="col-12 mt-2">
            <span class="form-text">(*) Campo requerido</span>
          </div>
        </div>
      </div>
      <div class="card-footer d-flex justify-content-end">
        <button type="submit" class="btn btn-success">Guardar cambios</button>
      </div>
    </form>
  </div>
</div>

{% endblock %}

admin/src/web/templates/user/roles.html.jinja
{% extends "layout.html.jinja" %}

{% block title %}Roles de "{{ user.username }}"{% endblock %}

{% block main %}
<h1>Gestión de roles para usuario "{{ user.username }}"</h1>

<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#add_modal">
  <i class="bi bi-plus-lg"></i>
  Agregar rol
</button>

<!-- List -->
{% if user_roles_count > 0 %}
  <table class="table table-dark table-striped table-bordered table-hover table-responsive mt-3 align-middle">
    <thead>
      <tr>
        <th scope="col">Rol</th>
        <th scope="col">Institución</th>
        <th scope="col">Acciones</th>
      </tr>
    </thead>
    <tbody>
      {% for ur in user_roles %}
        <tr>
          <td>{{ ur.role.name }}</td>
          <td>{% if ur.inst %}{{ ur.inst.name }}{% else %}(no aplica){% endif %}</td>
          <td>
            {% if ur.role.name != "Super Administrador" %}
              <a class="btn btn-outline-light" data-bs-toggle="modal" data-bs-target="#remove_modal_{{ ur.id }}"><i class="bi bi-trash"></i></a>
            {% endif %}
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% else %}
  <h2 class="mt-3">No hay ningún rol para mostrar</h2>
{% endif %}

<!-- Add -->
<div class="modal modal-lg fade" id="add_modal" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5">Agregar rol</h1>
      </div>
      <form action="{{ url_for('user.role.add', userid=user.id) }}" method="post">
        <div class="modal-body">
          <div class="row g-3">
            <div class="col-md-6">
              <label for="add_role_select" class="form-label">Rol:</label>
              <select class="form-select" id="add_role_select" name="roleid">
                {% for r in roles %}
                  {% if r.name != "Super Administrador" %}
                    <option value="{{ r.id }}">{{ r.name }}</option>
                  {% endif %}
                {% endfor %}
              </select>
            </div>
            <div class="col-md-6">
              <label for="add_inst_select" class="form-label">Institución:</label>
              <select class="form-select" id="add_inst_select" name="instid">
                {% for i in insts %}
                  <option value="{{ i.id }}">{{ i.name }}</option>
                {% endfor %}
              </select>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
          <button type="submit" class="btn btn-success">Guardar</button>
        </div>
      </form>
    </div>
  </div>
</div>

<!-- Remove -->
{% for ur in user_roles %}
  <div class="modal modal-lg fade" id="remove_modal_{{ ur.id }}" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Eliminar rol</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form action="{{ url_for('user.role.remove', userid=user.id, roleid=ur.role.id, instid=(ur.inst and ur.inst.id)) }}" method="post">
          <div class="modal-body">
            <p class="mb-0">¿Está seguro que desea eliminar el rol "{{ ur.role.name }}" en la institución "{{ ur.inst.name }}"?</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
            <button type="submit" class="btn btn-danger">Aceptar</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endfor %}

{% endblock %}

admin/src/web/templates/user/user.html.jinja
{% extends "layout.html.jinja" %}

{% block title %}Usuarios{% endblock %}

{% block main %}

<!-- List -->
{% if user_count > 0 %}
<table class="table table-dark table-striped table-bordered table-hover table-responsive mt-3 align-middle">
  <thead>
    <tr>
      <th scope="col">Nombre de usuario</th>
      <th scope="col">Email</th>
      <th scope="col">Nombre(s)</th>
      <th scope="col">Apellido(s)</th>
      <th scope="col">Activo</th>
      <th scope="col">Acciones</th>
    </tr>
  </thead>
  <tbody>
    {% for user in users %}
      <tr>
        <td>{{user.username}}</td>
        <td>{{user.email}}</td>
        <td>{{user.first_name}}</td>
        <td>{{user.last_name}}</td>
        <td>
          {% if user.activo %}
            Si
          {% else %}
            No
          {% endif %}
        </td>
        <td>
          <a class="btn btn-outline-light"><i class="bi bi-pencil-square"></i></a>
          <a class="btn btn-outline-light" data-bs-toggle="modal" data-bs-target="#delete_modal_{{ user.id }}"><i class="bi bi-trash"></i></a>
        </td>
      </tr>
    {% endfor %}
  </tbody>
</table>
<nav>
  <ul class="pagination">
    {% if page <= 1 %}
      <li class="page-item disabled">
        <a class="page-link"><i class="bi bi-arrow-left"></i></a>
      </li>
    {% else %}
      <li class="page-item">
        <a class="page-link" href="{{ url_for('user.index', page=(page - 1)) }}"><i class="bi bi-arrow-left"></i></a>
      </li>
    {% endif %}
    {% for i in range(1, page_count + 1) %}
      <li class="page-item{% if i == page %} active{% endif %}">
        <a class="page-link" href="{{ url_for('user.index', page=i) }}">{{i}}</a>
      </li>
    {% endfor %}
    {% if page >= page_count %}
      <li class="page-item disabled">
        <a class="page-link"><i class="bi bi-arrow-right"></i></a>
      </li>
    {% else %}
      <li class="page-item">
        <a class="page-link" href="{{ url_for('user.index', page=(page + 1)) }}"><i class="bi bi-arrow-right"></i></a>
      </li>
    {% endif %}
  </ul>
</nav>
{% else %}
<h1>Todavía no hay usuarios registrados</h1>
{% endif %}
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#create_modal">
  <i class="bi bi-plus-lg"></i>
</button>

<!-- Create -->
<div class="modal modal-lg fade" id="create_modal" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5">Crear usuario</h1>
      </div>
      <form action="{{ url_for('user.create') }}" method="post">
        <div class="modal-body">
          <div class="mb-3">
            <label for="create_username" class="form-label">Nombre de usuario</label>
            <input type="text" class="form-control" id="create_username" name="username">
          </div>
          <div class="mb-3">
            <label for="create_email" class="form-label">Email</label>
            <input type="email" class="form-control" id="create_email" name="email">
          </div>
          <div class="mb-3">
            <label for="create_first_name" class="form-label">Nombre(s)</label>
            <input type="text" class="form-control" id="create_first_name" name="first_name">
          </div>
          <div class="mb-3">
            <label for="create_last_name" class="form-label">Apellido(s)</label>
            <input type="text" class="form-control" id="create_last_name" name="last_name">
          </div>
          <div class="mb-3">
            <label for="create_password" class="form-label">Contraseña</label>
            <input type="password" class="form-control" id="create_password" name="password">
          </div>
          <div class="mb-3">
            <label for="create_password_repeat" class="form-label">Repetir contraseña</label>
            <input type="password" class="form-control" id="create_password_repeat" name="password_repeat">
          </div>
          <div class="mb-3 form-check">
            <input type="checkbox" class="form-check-input" id="create_active" name="active" checked>
            <label class="form-check-label" for="create_active">Activo</label>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
          <button type="submit" class="btn btn-primary">Guardar</button>
        </div>
      </form>
    </div>
  </div>
</div>

<!-- Delete -->
{% for user in users %}
  <div class="modal modal-lg fade" id="delete_modal_{{ user.id }}" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Eliminar usuario</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form action="{{ url_for('user.delete', userid=user.id) }}" method="post">
          <div class="modal-body">
            <p class="mb-0">¿Está seguro que desea eliminar el usuario "{{ user.username }}"?</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
            <button type="submit" class="btn btn-danger">Aceptar</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endfor %}

{% endblock %}