admin/src/web/controllers/auth_controller.py
from flask import Blueprint,redirect, render_template, request, url_for, session, flash 
from src.core.models.user_model import User
from src.core.models.config_model import Config
from src.web.helpers.auth import login_required


auth_blueprint = Blueprint("auth", __name__, url_prefix="/auth")


@auth_blueprint.get("/")   
def login():
    return render_template("auth/login.html.jinja")


@auth_blueprint.post("/authenticate")   
def authenticate():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        user = User.check_user(username, password)   
        config = Config.get_singleton()
        if not config.state and user.username != "super":
            flash(config.information, "danger")  
            return redirect(url_for("home"))          
        else:
            if user:
                if user.activo:
                    session['user_id'] = user.id
                    return redirect(url_for("home"))
                elif user.activo == False:
                    flash("El usuario se encuentra desactivado", "danger")      
            else:
                flash("El nombre de usuario o contraseña es incorrecto", "danger")

    return render_template("auth/login.html.jinja")               

# Al acceder a la ruta "/LOGOUT", la sesión se destruirá y el usuario será redirigido 
# a la página principal sin la variable de sesión "usuario". 
@auth_blueprint.get("/logout")
def logout():
    session.pop('google_token', None)
    session.clear()
    return redirect(url_for("home"))

admin/src/web/controllers/config_controller.py
from flask import Blueprint,redirect, render_template, request, url_for, session, flash 
from src.core.models.config_model import Config
from src.core.models import create_config
from src.web.helpers.auth import login_required, has_permission
from src.web.helpers.validations import verify_space, verify_vacio, validate_email_config

config_blueprint = Blueprint("config", __name__, url_prefix="/config")

@config_blueprint.get("/") 
@login_required
@has_permission("config_show")
def index():
    config = Config.get_singleton()

    return render_template("config.html.jinja", config=config)

@config_blueprint.post("/config")
@login_required
@has_permission("config_update")
def update():
   config = Config.get_singleton()

   if verify_vacio(items = request.form.items()):
      if verify_space(items = request.form.items()) :  
         if request.form['cant']:  
            cant = request.form['cant']
         if request.form['contact']:  
            contact = request.form['contact']
         if request.form['email']:     
            email = request.form['email']
         if request.form['state']:  
            state = request.form['state'].lower() == "true"
         if request.form['information']:     
            information = request.form['information']
         if validate_email_config(email)and int(cant) > 0:
            flash("Se actualizo el valor del campo editado", "success")
            config.update_config_database(cant,contact,email,state,information)
      else:
         flash("No se puedo guardar, Actualize bien los campos", "danger")   
   else:
      flash("No se puedo guardar campos vacios", "danger")




   return redirect(url_for("config.index"))

admin/src/web/controllers/inst_controller.py
from flask import Blueprint, redirect, session, url_for
from src.core.models.institution_model import Institution


inst_blueprint = Blueprint("inst", __name__, url_prefix="/inst")


@inst_blueprint.get("/change/<int:instid>")
def change(instid):
    inst = Institution.find_by_id(instid)
    if inst and inst.activo:
        session["inst_id"] = inst.id
    else:
        abort(404)
    
    return redirect(url_for("home"))

admin/src/web/controllers/user_controller.py
import json
import math
from flask import abort, Blueprint, redirect, render_template, request, url_for, session, flash
from flask_mail import Message
from src.core.models import crear_usuario
from src.core.models.user_model import User
from src.core.models.role_model import Role
from src.core.models.institution_model import Institution
from src.core.models.config_model import Config
from src.core.bcrypt import bcrypt
from src.web.mail import mail
from src.web.helpers.auth import login_required, has_permission
from src.web.helpers.validations import (
    validate_email,
    validate_username,
    validate_password,
    validate_first_name,
    validate_last_name,
    validate_active
)
from src.web.helpers.session import get_current_user
from src.web.helpers.tokens import get_serializer


user_blueprint = Blueprint("user", __name__, url_prefix="/user")

role_blueprint = Blueprint("role", __name__, url_prefix="/role")
user_blueprint.register_blueprint(role_blueprint)


@user_blueprint.get("/")
@user_blueprint.get("/<int:page>")
@login_required
@has_permission("user_index")
def index(page=1):
    page_size = Config.get_singleton().cant

    users, users_count = User.paginate(page, page_size, request.args.get("email"), request.args.get("filter"))
    page_count = math.ceil(users_count / page_size)

    return render_template(
        "user/index.html.jinja",
        users=users,
        users_count=users_count,
        page=page,
        page_count=page_count,
        filter_email=request.args.get("email", ""),
        filter_active=request.args.get("filter", "")
    )


def create_update(user=None, arglist=None):
    form = request.form

    if isinstance(user, int):
        user = User.get(user)

    args = {
        'email': validate_email,
        'username': validate_username,
        'password': validate_password,
        'first_name': validate_first_name,
        'last_name': validate_last_name,
        'activo': validate_active
    }

    kwargs = {}
    for key, fn in args.items():
        if arglist and key not in arglist:
            continue
        value, *err = fn(form, user)
        if value is None:
            if len(err) > 0:
                flash(err[0], "danger")
            break
        kwargs[key] = value
    else:
        if user:
            if user.has_role(Role.get_by_name("Super Administrador")) and args['activo'](form, user)[0] == False:
                flash("No se puede deshabilitar el usuario superadministrador", "danger")
                return None
            user.update(**kwargs)
        else:
            user = crear_usuario(**kwargs)
        return user
        
    return None


@user_blueprint.post("/create")
@login_required
@has_permission("user_create")
def create():
    if create_update():
        flash("¡Se creó el usuario de manera exitosa!", "success")
    
    return redirect(url_for("user.index"))


@user_blueprint.post("/update/<int:userid>")
@login_required
@has_permission("user_update")
def update(userid):
    arglist = ['email', 'username', 'first_name', 'last_name', 'activo']
    if request.form.get('change_password'):
        arglist.append('password')
        
    if create_update(userid, arglist):
        flash("¡Se actualizó el usuario de manera exitosa!", "success")
    
    return redirect(url_for("user.index"))


@user_blueprint.post("/delete/<int:userid>")
@login_required
@has_permission("user_destroy")
def delete(userid):
    user = User.get(userid)
    if user:
        if user.has_role(Role.get_by_name("Super Administrador")):
            flash("No se puede eliminar el usuario superadministrador", "danger")
        else:
            user.delete()
    else:
        flash(f"No se pudo eliminar el usuario con ID: {userid}")
    
    return redirect(url_for("user.index"))


@role_blueprint.get("/<int:userid>", endpoint="index")
@login_required
@has_permission("user_index")
def role_index(userid):
    user = User.get(userid)
    if not user:
        abort(404)
    
    roles = Role.get_all()
    insts = Institution.get_all()

    user_roles = []
    for ur in user.get_roles():
        user_roles.append({
            "role": Role.find_by_id(ur.role_id),
            "inst": Institution.find_by_id(ur.institution_id),
            "id": f"r{ur.role_id}-i{ur.institution_id or 0}"
        })
    
    user_roles_count = len(user_roles)
    
    return render_template(
        "user/roles.html.jinja",
        user=user,
        roles=roles,
        insts=insts,
        user_roles=user_roles,
        user_roles_count=user_roles_count
    )


@role_blueprint.post("/<int:userid>/add", endpoint="add")
@login_required
@has_permission("user_update")
def role_add(userid):
    user = User.get(userid)
    if not user:
        abort(404)
    
    roleid = request.form.get("roleid")
    role = Role.find_by_id(roleid) if roleid else None
    if not role:
        abort(404)
    
    if role.name == "Super Administrador":
        abort(404)
    
    instid = request.form.get("instid")
    inst = Institution.find_by_id(instid) if instid else None
    if not inst:
        abort(404)
    
    if user.has_role(role, inst):
        flash("Ya existe un rol similar para el usuario", "danger")
    else:
        user.add_role(role, inst)
        
    return redirect(url_for("user.role.index", userid=user.id))


@role_blueprint.post("/<int:userid>/remove/<int:roleid>", endpoint="remove")
@role_blueprint.post("/<int:userid>/remove/<int:roleid>/<int:instid>", endpoint="remove")
@login_required
@has_permission("user_update")
def role_remove(userid, roleid, instid=None):
    user = User.get(userid)
    if not user:
        abort(404)

    role = Role.find_by_id(roleid)
    if not role:
        abort(404)
    
    if role.name == "Super Administrador":
        abort(404)

    if instid:
        inst = Institution.find_by_id(instid)
        if not inst:
            abort(404)
    else:
        inst = None

    ok = user.remove_role(role, inst)
    if not ok:
        flash("No se pudo eliminar el rol", "danger")
    
    return redirect(url_for("user.role.index", userid=user.id))


@user_blueprint.route("/register", methods=["GET", "POST"])  
def register():
    if request.method == 'POST':
        user = create_update(arglist=['email', 'first_name', 'last_name'])
        if user:
            ser = get_serializer("confirmation")
            tok = ser.dumps({"user_id": user.id})

            msg = Message(
                "Confirmación de usuario",
                recipients=[user.email]
            )
            msg.html = render_template('email.html.jinja', token=tok)
            mail.send(msg)

            flash(
                "Le enviamos un enlace de confirmación a su casilla de correo electrónico. "
                "Por favor, confirme su correo antes de iniciar sesión.",
                "warning"
            )

            return redirect(url_for("auth.login"))
        else:
            return redirect(url_for("user.register"))
    elif request.method == 'GET':
        return render_template('register_user.html.jinja')


@user_blueprint.route("/confirm/<token>", methods=["GET", "POST"])
def confirm(token):
    try:
        ser = get_serializer("confirmation")
        data = ser.loads(token)
    except:
        abort(404)
    
    user_id = data.get('user_id')
    if user_id is None:
        abort(404)

    user = User.find_by_id(data['user_id'])
    if user is None:
        abort(404)
    
    if user.exists:
        abort(404)
    
    if request.method == 'POST':
        if create_update(user=user, arglist=['username', 'password']):
            flash("¡Su usuario ha sido confirmado exitosamente!", "success")
            return redirect(url_for("auth.login"))

    return render_template("user/confirm.html.jinja", token=token, user=user)


@user_blueprint.route("/profile", methods=["GET", "POST"]) 
@login_required  
def profile():
    user = get_current_user()
    if not user:
        abort(404)

    if request.method == "POST":
        arglist = ['username', 'first_name', 'last_name']
        if request.form.get('change_password'):
            arglist.append('password')
            
        if create_update(user=user, arglist=arglist):
            flash("¡Se actualizaron sus datos de manera exitosa!", "success")
    
    return render_template('user/profile.html.jinja', user=user)

admin/src/web/templates/complete_registration.html.jinja
{% extends "layout.html.jinja" %}

{% block title %}Completar Registro{% endblock %}

{% block main %}
<div class="container mt-5">
    <h2>Completar Registro</h2>
    <p>Completa tu registro proporcionando la información adicional requerida:</p>

    <p><strong>Email:</strong> {{ user_info['email'] }}</p>
    <p><strong>Nombre:</strong> {{ user_info['given_name'] }}</p>
    <p><strong>Apellido:</strong> {{ user_info['family_name'] }}</p>

    <form action="{{ url_for('google_auth.complete_registration') }}" method="post" class="needs-validation" novalidate>
        <div class="row g-3 d-flex flex-column">
            <div class="col-12">
                <label class="form-label" for="username">*Nombre de Usuario:</label>
                <input class="form-control" type="text" id="username" name="username"
                    pattern="[a-zA-Zá-úÁ-ÚñÑ][a-zA-Zá-úÁ-ÚñÑ0-9._]{2,18}[a-zA-Zá-úÁ-ÚñÑ0-9]" required>
                <div class="invalid-feedback">
                    Por favor, ingrese un nombre de usuario válido.
                    <br>
                    El nombre de usuario debe tener entre 4 y 20 letras, dígitos, '.' y '_'.
                    <br>
                    No puede comenzar con números o símbolos ni terminar en símbolos.
                </div>
            </div>
            <div class="d-flex flex-column flex-lg-row mt-3">
                <div class="w-100">
                    <label class="form-label" for="password">*Contraseña:</label>
                    <input class="form-control password-field" type="password" id="password" name="password"
                        pattern="[^ ]{4,32}" required>
                    <div class="invalid-feedback">
                        Por favor, ingrese una contraseña válida.
                        <br>
                        Las contraseñas deben tener entre 4 y 32 carácteres, no pueden tener espacios.
                    </div>
                </div>

                <div class="w-100">
                    <label class="form-label" for="password_repeat">*Confirmar Contraseña:</label>
                    <input class="form-control confirm-password-field" type="password" id="password_repeat"
                        name="password_repeat" required>
                    <div class="invalid-feedback">
                        Por favor, repita la contraseña aquí. Las contraseñas deben coincidir.
                    </div>
                </div>
            </div>
            <div class="mt-3">
                <a class="btn btn-primary btn-lg btn-block" href="{{ url_for('home') }}" role="button">Cancelar</a>
                <button type="submit" class="btn btn-success btn-lg btn-block"><i
                        class="fa fa-save me-1"></i>Registrar</button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

admin/src/web/templates/config.html.jinja
{% extends "layout.html.jinja" %}

{% block main %}

<!-- Iconos fontawesome -->
<link rel="stylesheet" href="{{ url_for('static', filename='fontawesome/css/all.css') }}">




  <main id="main">
<div class="d-flex align-items-center flex-column mt-3 pb-5 justify-content-center w-100 h-100">
  <div class="d-flex align-items-center flex-column justify-content-center w-100 own_form_title">
    
    <div class="d-flex flex-column mt-5 justify-content-center align-items-center own_form_title w-100">
       <h1>Mi configuración </h1>
    </div>
  </div>
  <div class="container mt-3 own_form align-items-center" style="max-width: 800px">
    
  <form action="{{ url_for('config.update') }}" method="post" class="d-flex flex-column">

    <div class="form-group">
      <label class="form-label" for="cant">Cantidad de filas por página:</label>
      <input class="form-control" id="cant" min="1" name="cant"  type="number" value="{{config.cant}}">
    </div>
    
    <div class="form-group">
      <label class="form-label" for="contact">Información de contacto:</label>
      <input class="form-control" id="contact" name="contact"  type="text" value="{{config.contact}}">
    </div>

    <div class="form-group">
      <label class="form-label" for="email">Información de email:</label>
      <input class="form-control" id="email" name="email"  type="text" value="{{config.email}}">
    </div>

    <div class="form-group">
      <label class="form-label" for="state">opcion para Activar/Desactivar sistema:</label>
      <select class="form-select" id="state" name="state">
      {% if config.state %}
        <option selected value="True">Habilitado</option>
        <option value="False">Deshabilitado</option>
      {% else %}
        <option value="True">Habilitado</option>
        <option selected value="False">Deshabilitado</option>
      {% endif %}

      </select>
    </div>
    
    
    <div class="form-group">
      <label class="form-label" for="information">Mensaje de Mantenimiento:</label>
      <input class="form-control" id="information" name="information" required type="text" value="{{config.information}}">
    </div>


    <br>
    <button type="submit" class="btn btn-success btn-lg btn-block mt-3"><i class="fa fa-save"></i> Guardar</button>
    
    
  </form>
  
{% endblock %}

admin/src/web/templates/email.html.jinja
<h1>¡Bienvenido al portal de CIDEPINT!</h1>
<p>
    Por favor, haga click en el siguiente enlace para confirmar su usuario:
    <a href="{{ url_for('user.confirm', token=token, _external=True) }}">enlace</a>.
</p>

admin/src/web/templates/error.html.jinja
{% extends "layout.html.jinja" %}

{% block main %}
<style>
    /* Estilos personalizados para la página de error 404 */
    .error-container {
        text-align: center;
        margin-top: 100px;
    }
    .error-containerLeft {
       text-align: left;
       margin-top: 100px;
    }

    .error-title {
        font-size: 36px;
        color: #007A5E;
        /* Verde oscuro similar al color de la bandera argentina */
    }

    .error-description {
        font-size: 24px;
        color: black;
        margin-top: 20px;
    }

    /* Estilo personalizado para resaltar la victoria de Argentina */
    .argentina-champion {
        font-weight: bold;
        font-size: 28px;
        color: #75AADB;
        /* Azul claro */
        margin-top: 10px;
    }

    /* Estilo para animar los mensajes */
    .not-found-message {
        font-size: 48px;
        color: #FF5733;
        /* Rojo */
        animation: moveText 2s linear infinite alternate;
    }

    @keyframes moveText {
        from {
            transform: translateY(-5px);
        }

        to {
            transform: translateY(5px);
        }
    }
</style>

<script>
    // JavaScript para mostrar ambos mensajes al mismo tiempo
    document.addEventListener('DOMContentLoaded', function () {
        const message1 = document.querySelector('.message-1');
        const message2 = document.querySelector('.message-2');

        message1.style.display = 'block'; // Mostrar el primer mensaje
        message2.style.display = 'block'; // Mostrar el segundo mensaje
    });
</script>
<div class= "error-containerLeft"> 
        <h1 class="error-title">{{ error_name }}</h1>
        <p class="error-description">{{ error_description }} 😞</p>
</div>
<div class="error-container">
    <!-- Mensaje 1 (Página no encontrada) -->
    <p class="not-found-message message-1">Página no encontrada</p>

    <!-- Mensaje 2 (404 Not Found) -->
    <p class="not-found-message message-2">404 Not Found</p>
    <p class="argentina-champion">Pero te recodamos que...</p>
    <p class="argentina-champion">¡Argentina Campeona del Mundo!</p>
    <img src="static/imagenes/argentinaCampeon.jpg" alt="Imagen de la selección argentina campeona del mundo">
</div>

{% endblock %}

admin/src/web/templates/home.html.jinja
{% extends "layout.html.jinja" %}

{% block title %}Home{% endblock %}

{% block main %}

{% if is_authenticated() %}
<h1>¡Bienvenido, {{ get_current_user().username}}!</h1>
{% endif %}

<br>
<div class="container-fluid d-flex justify-content-center">
    <div class="slider">
        <img src="{{ url_for('static', filename='Imagenes/home.jpg') }}" alt="">
    </div>
</div>
{% endblock %}

admin/src/web/templates/layout.html.jinja
<!DOCTYPE html>
<html lang="es">

<head>
  {% block head %}
  <meta charset="UTF-8">
  <meta name="description" content="Sitio de administración CIDEPINT">
  <meta name="keywords" content="CIDEPINT">
  <meta name="author" content="Grupo 12 - Proyecto de Software - UNLP">
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css">
  <link rel="stylesheet" href="{{ url_for('static', filename='layout.css') }}" />
  <!-- Iconos fontawesome -->
  <link rel="stylesheet"
    href="{{ url_for('static', filename='fontawesome/fontawesome-free-6.4.2-web/css/all.min.css') }}">

  <title>{% block title %}{% endblock %} - CIDEPINT</title>
  {% endblock %}
</head>

<body class="container bg-dark d-flex flex-column" data-bs-theme="dark">
  <header class="mb-3">
    <nav class="navbar sticky-top navbar-expand-lg bg-body-tertiary navbar bg-dark border-bottom border-body"
      data-bs-theme="dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">CIDEPINT</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
          aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0 d-flex justify-content-between" id="nav-items">
            <div class="d-flex flex-column flex-lg-row">
              {% if is_authenticated() %}
              <div class="d-flex align-items-center">
                <li class="nav-item">
                  {% with institutions = list_institutions() %}
                  {% if institutions|length > 0 %}
                  <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown">
                      {{ get_current_institution().name or "Institución" }}
                    </button>
                    <ul class="dropdown-menu">
                      {% for inst in institutions %}
                      <li><a class="dropdown-item {% if inst.id == session.get('inst_id') %}active{% endif %}"
                          href="{{ url_for('inst.change', instid=inst.id) }}">
                          {{ inst.name }}
                        </a></li>
                      {% endfor %}
                    </ul>
                  </div>
                  {% endif %}
                  {% endwith %}
                </li>
                {% if get_current_institution() %}
                {% if check_permission("role_index") %}
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('role.index') }}">Roles</a>
                </li>
                {% endif %}
                {% if check_permission("service_index") %}
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('service.index') }}">Servicios</a>
                </li>
                {% endif %}
                {% if check_permission("request_index") %}
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('service_request.index') }}">Solicitudes de Servicios</a>
                </li>
                {% endif %}
                {% endif %}
              </div>
              {% endif %}
            </div>
            {% if is_authenticated()%}
            <div class="d-flex flex-column flex-lg-row">
              {% if is_superadmin() %}
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('user.index') }}">Usuarios</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('institutions.index') }}">Instituciones</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('config.index') }}">Configuracion</a>
              </li>
              {% endif %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">
                  <i class="bi bi-person-fill"></i> {{ get_current_user().username }}
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{{ url_for('user.profile') }}">Perfil</a></li>
                  <li><a class="dropdown-item" href="{{ url_for('auth.logout') }}">Cerrar sesión</a></li>
                </ul>
              </li>
            </div>
            {% else %}
            <div class="d-flex flex-column flex-lg-row">
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('auth.login') }}">Iniciar sesión</a>
              </li>
              <li class="nav-item">
                <a href="{{ url_for('user.register') }}"><button type="button"
                    class="btn btn-light">Registrarse</button></a>
              </li>
            </div>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <main class="container">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-{{category}} alert-dismissible fade show" role="alert">
      <strong>{{ message }}</strong>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}

    {% block main %}
    {% endblock %}
  </main>
  <footer class="bg-dark text-white text-center py-3 border-top">
    <div class="container">
      <p>&copy; 2023 - Grupo 12</p>
    </div>
  </footer>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous">
    </script>
  <script>
    (() => {
      'use strict'

      const forms = document.querySelectorAll('.needs-validation')

      Array.from(forms).forEach(form => {
        const password = form.querySelector('.password-field')
        const confirmPassword = form.querySelector('.confirm-password-field')
        const changePassowrd = form.querySelector('.change-password')

        if (password && confirmPassword) {
          confirmPassword.addEventListener('input', event => {
            if (password.value != confirmPassword.value) {
              confirmPassword.setCustomValidity("Las contraseñas deben coincidir.")
            } else {
              confirmPassword.setCustomValidity("")
            }
          });
        }

        if (changePassowrd) {
          changePassowrd.addEventListener("change", function (e) {
            if (changePassowrd.checked) {
              password.removeAttribute("disabled");
              confirmPassword.removeAttribute("disabled");
            } else {
              password.setAttribute("disabled", true)
              confirmPassword.setAttribute("disabled", true)
            }
          })
        }

        form.addEventListener('submit', event => {
          if (!form.checkValidity()) {
            event.preventDefault()
            event.stopPropagation()
          }

          form.classList.add('was-validated')
        }, false)
      })
    })()
  </script>
  {% block script %}
  {% endblock %}
</body>

</html>

admin/src/web/templates/register_user.html.jinja
{% extends "layout.html.jinja" %}

{% block title %} Registrar {% endblock %}

{% block main %}
<div class="d-flex flex-column justify-content-center align-items-center">
  <div class="card mb-3">
    <div class="card-header">
      <h2>Registrarse</h2>
    </div>
    <form action="{{ url_for('user.register') }}" method="POST" class="needs-validation" novalidate>
      <div class="card-body">
        <div class="row g-3">
          <div class="col-12">
            <label for="email" class="form-label">Email</label>
            <input type="email" class="form-control" id="email" name="email" required>
            <div class="invalid-feedback">
              Por favor, ingrese una dirección de correo electronico válida.
            </div>
          </div>
          <div class="col-md-6">
            <label for="first_name" class="form-label">Nombre/s (*)</label>
            <input type="text" class="form-control" id="first_name" name="first_name" pattern="[a-zA-Zá-úÁ-ÚñÑ][a-zA-Zá-úÁ-ÚñÑ ]{0,22}[a-zA-Zá-úÁ-ÚñÑ]" required>
            <div class="invalid-feedback">
              Por favor, ingrese un nombre válido.
              <br>
              Los nombres solo pueden contener letras y espacios.
              <br>
              No pueden comenzar ni terminar con espacios.
            </div>
          </div>
          <div class="col-md-6">
            <label for="last_name" class="form-label">Apellido/s (*)</label>
            <input type="text" class="form-control" id="last_name" name="last_name" pattern="[a-zA-Zá-úÁ-ÚñÑ][a-zA-Zá-úÁ-ÚñÑ ]{0,22}[a-zA-Zá-úÁ-ÚñÑ]" required>
            <div class="invalid-feedback">
              Por favor, ingrese un apellido válido.
              <br>
              Los apellidos solo pueden contener letras y espacios.
              <br>
              No pueden comenzar ni terminar con espacios.
            </div>
          </div>
          <div class="col-12 mt-2">
            <span class="form-text">(*) Campo requerido</span>
          </div>
        </div>
      </div>
      <div class="card-footer d-flex justify-content-end">
        <button class="btn btn-secondary" onclick="history.back()">Volver</button>
        <button type="submit" class="btn btn-success ms-2">Registrarse</button>
      </div>
    </form>
  </div>
  <button type="button" class="btn btn-outline-danger mb-3"
    onclick="window.location.href='{{url_for('google_auth.login_google')}}'">
    <i class="fab fa-google"></i> Ingresar con Google
  </button>
</div>
{% endblock %}